name: transfer_ski10

defaults_from: main.yaml

data:
  name: ski10
  root: ./data/ski10
  manifests_dir: ./data/manifests/ski10
  target_shape: [160, 384, 384]
  batch_size: 1
  num_workers: 4

model:
  num_seg_classes: 5

train:
  epochs: 0
  seed: 42
